-- 초기 스키마.
--
-- 현재 엔티티로 Hibernate가 생성한 PostgreSQL DDL을 옮긴 것이다. 손으로 쓰면 엔티티와
-- 어긋나고, 어긋나면 ddl-auto: validate 가 배포를 막는다.
--
-- 이 파일은 이미 적용됐으므로 수정하지 않는다. 스키마가 바뀌면 V2, V3으로 파일을 추가한다.
-- Flyway가 체크섬을 검증해서, 적용된 파일을 고치면 다음 기동에서 실패한다.

create table users (
    id                bigint       generated by default as identity,
    google_sub        varchar(255) not null unique,
    email             varchar(255),
    name              varchar(255),
    profile_image_url varchar(255),
    created_at        timestamp(6),
    updated_at        timestamp(6),
    primary key (id)
);

create table groups (
    id            bigint       generated by default as identity,
    group_name    varchar(255) not null,
    group_host_id bigint       not null,
    join_code     varchar(255) not null unique,
    group_status  varchar(255) not null check (group_status in ('ACTIVE', 'INACTIVE')),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    deleted_at    timestamp(6),
    primary key (id)
);

create table group_members (
    id         bigint generated by default as identity,
    group_id   bigint not null,
    user_id    bigint not null,
    role       varchar(255) check (role in ('OWNER', 'MEMBER')),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint fk_group_members_group foreign key (group_id) references groups,
    constraint fk_group_members_user foreign key (user_id) references users
);

create table events (
    id                bigint       generated by default as identity,
    group_id          bigint       not null,
    title             varchar(100) not null,
    description       text,
    start_at          timestamp(6) not null,
    end_at            timestamp(6) not null,
    initial_budget    bigint       not null,
    participant_count integer,
    status            varchar(20)  not null check (status in ('ACTIVE', 'CLOSED')),
    closed_at         timestamp(6),
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    primary key (id)
);

create table budget_additions (
    id         bigint       generated by default as identity,
    event_id   bigint       not null,
    amount     bigint       not null,
    reason     text         not null,
    created_by bigint       not null,
    created_at timestamp(6) not null,
    primary key (id)
);

create table spendings (
    id                   bigint       generated by default as identity,
    event_id             bigint       not null,
    applicant_user_id    bigint       not null,
    amount               bigint       not null,
    reason               text         not null,
    spent_on             date         not null,
    tag                  varchar(20)  not null check (tag in
                                                      ('MEAL', 'ACCOMMODATION', 'TRANSPORTATION',
                                                       'VENUE', 'SUPPLIES', 'OTHER')),
    other_detail         text,
    status               varchar(20)  not null check (status in ('PENDING', 'APPROVED', 'REJECTED')),
    rejection_reason     text,
    processed_by_user_id bigint,
    processed_at         timestamp(6),
    evidence_type        varchar(20)  not null check (evidence_type in ('RECEIPT', 'BANK_TRANSFER')),
    evidence_storage_key text         not null,
    evidence_mime_type   varchar(50)  not null,
    evidence_file_size   bigint,
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    primary key (id)
);

-- snapshot: 확정된 결산 내용을 JSONB로 통째로 보관한다.
-- 원본 지출이 나중에 바뀌어도 보고서 수치는 변하지 않아야 하므로 값을 복사해 굳힌다.
--
-- event_id unique: 행사당 보고서는 하나다. 재생성은 새 행을 만들지 않고 기존 행을 다시 쓴다.
create table reports (
    id                bigint       generated by default as identity,
    event_id          bigint       not null,
    status            varchar(20)  not null check (status in
                                                   ('PENDING', 'GENERATING', 'COMPLETED', 'FAILED')),
    ai_status         varchar(20)  not null check (ai_status in ('PENDING', 'SUCCEEDED', 'FAILED')),
    ai_summary        text,
    snapshot          jsonb,
    total_budget      bigint       not null,
    total_spent       bigint       not null,
    remaining_balance bigint       not null,
    pdf_file_key      varchar(512),
    csv_file_key      varchar(512),
    failure_reason    varchar(500),
    retry_count       integer      not null,
    generated_at      timestamp(6),
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    primary key (id),
    constraint uk_reports_event_id unique (event_id)
);
